# Generated by Django 5.0.3 on 2024-04-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('created_dt', models.DateField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateField(auto_now=True, verbose_name='MODIFY DATE')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.menu')),
            ],
            options={
                'ordering': ('-created_dt',),
            },
        ),
    ]
