# Generated by Django 5.0.3 on 2024-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='temperature',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
