# Generated by Django 5.0.3 on 2024-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_order_option_alter_order_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_dt',)},
        ),
    ]
